title: My Portfolio
description: A showcase of my projects, skills, and contact information.
author: Nathanael Nienaber

remote_theme: pages-themes/slate@v0.2.0

# URL and Base Path
url: https://nathanaelnienaber.github.io

# Markdown Processing
markdown: kramdown
kramdown:
  input: GFM  # GitHub-Flavored Markdown

# Navigation Links (Optional)
nav_links:
  - title: Home
    url: /
  - title: About
    url: /about    # Consistent with header.html
  - title: Projects
    url: /projects
  - title: Contact
    url: /contact

# Output Options
permalink: pretty






